FROM node:22.18.0
WORKDIR /qo-uiapi
ENV NODE_OPTIONS=--max-old-space-size=4096
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps || npm install --legacy-peer-deps
COPY . .
RUN npm run build:uat
RUN npm install -g pm2
WORKDIR /qo-uiapi/build
EXPOSE 3210
CMD ["pm2-runtime", "start", "server.js", "-i", "2"]
