replicaCount: 1

image:
  repository: harbor.q0.dev/yotta-q0/q0-dev-app-service
  tag: "App_svc_Dev_1"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-registry-secret

container:
  name: q0-uiapi
  ports:
    - name: http
      containerPort: 3210
    - name: secondary
      containerPort: 3220

service:
  name: q0-uiapi-service
  type: NodePort
  ports:
    - name: http
      port: 3210
      targetPort: 3210
    - name: secondary
      port: 3220
      targetPort: 3220
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /Infer/api/apiHealthCheck/apihealth

labels:
  app: q0-uiapi

resources:
  requests:
    cpu: "300m"
    memory: "0.25Gi"
  limits:
    cpu: "500m"
    memory: "0.5Gi"

probes:
  startup:
    httpGet:
      path: /Infer/api/apiHealthCheck/apihealth
      port: http
    failureThreshold: 5
    initialDelaySeconds: 20
    periodSeconds: 10
  liveness:
    httpGet:
      path: /Infer/api/apiHealthCheck/apihealth
      port: http
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 30
  readiness:
    httpGet:
      path: /Infer/api/apiHealthCheck/apihealth
      port: http
    failureThreshold: 5
    initialDelaySeconds: 20
    periodSeconds: 10

progressDeadlineSeconds: 180

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}
